### ISSUE TITLE
rollup bundeling fails with fluid-player

### ISSUE THREAD

**Issue by schlingel** [fluid-player/fluid-player#573]
**Describe the bug**
Building a `iife` package with rollup fails due to this error:

```
(!) `this` has been rewritten to `undefined`  
```

**To Reproduce**
1. Create very simple script with rollup build script
2. run `rollup -c rollup.config.js`

*rollup.config.js*
```
import { nodeResolve } from '@rollup/plugin-node-resolve';

export default {
    input: 'main.js',
    output: {
        file: 'bundle.js',
        format: 'iife'
    },
    plugins: [
        nodeResolve({ browser: true }),
    ],
}
```

*main.js*
```
import fluidPlayer from 'fluid-player';

console.log('Test');
```

**Expected behavior**
fluidPlayer should be properly packaged in self contained bundle. 

**Screenshots or Links**

Error-Log:
```
                                                                                             
player/src/main.js → bundle.js...                                                                                     
(!) `this` has been rewritten to `undefined`                                                                          
https://rollupjs.org/guide/en/#error-this-is-undefined                                                                
node_modules/es6-promise/dist/es6-promise.js                                                                          
11:   typeof define === 'function' && define.amd ? define(factory) :                                                  
12:   (global.ES6Promise = factory());                                                                                
13: }(this, (function () { 'use strict';                                                                              
      ^                                                                                                               
14:                                                                                                                   
15: function objectOrFunction(x) {                                                                                    
node_modules/hls.js/dist/hls.js                                                                                       
 9:   else                                                                                                            
10:     root["Hls"] = factory();                                                                                      
11: })(this, function() {                                                                                             
       ^                                                                                                              
12: return /******/ (function(modules) { // webpackBootstrap                                                          
13: /******/    // The module cache                                                                                   
[!] Error: 'default' is not exported by node_modules/es6-promise/dist/es6-promise.js, imported by node_modules/fluid-p
layer/src/polyfills.js                                                                                                
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module                                                   
node_modules/fluid-player/src/polyfills.js (3:7)    
1: 'use strict';
2: 
3: import promisePolyfill from 'es6-promise';
          ^
4: 
5: // Object.assign polyfill
Error: 'default' is not exported by node_modules/es6-promise/dist/es6-promise.js, imported by node_modules/fluid-player/src/polyfills.js
    at error (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:5309:30)
    at Module.error (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:9765:16)
    at Module.traceVariable (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:10151:29)
    at ModuleScope.findVariable (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:8905:39)
    at MemberExpression.bind (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:6576:49)
    at CallExpression.bind (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:2723:23)
    at CallExpression.bind (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:6767:15)
    at ExpressionStatement.bind (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:2723:23)
    at Program.bind (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:2719:31)
    at Module.bindReferences (/home/zombie/.nvm/versions/node/v12.13.1/lib/node_modules/rollup/dist/shared/rollup.js:9761:18)

**Affected version**
For example, v3.0.4

**Additional context**
    "rollup": "^2.47.0"
    "@rollup/plugin-node-resolve": "^13.0.0",

**Comment by leroybm** [comment]
Hi @schlingel, are you still having this issue? I've tried to bundle with the latest Fluid Player version, and 3.04, and it worked. I would recommend updating all dependencies and trying again.

Any way, Fluid Player uses webpack officially, I would recommend using it as we can provide better support.

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since we haven't received any response from the reporter.
