### ISSUE TITLE
Self-compilation of the project

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#592]
Hello, i used fluidplayer 2.0 a long time, and i want use 3.0 but self-hosted and customized for me. Can you write step by step instructions for compile fluidplayer?

Thank you

**Comment by gibigate** [comment]
There is errors while i try build project with "npm run build":
`
npm run build

> fluid-player@3.0.4 build /Users/admin/Documents/GitHub/fluid-player-3.0.4
> webpack --mode=production

Hash: 28ec44009cc5589c97dc
Version: webpack 4.46.0
Time: 516ms
Built at: 06/18/2021 4:07:28 PM
 1 asset
Entrypoint fluidplayer = fluidplayer.min.js
[0] ./src/browser.js 3.04 KiB {0} [not cacheable] [built] [failed] [1 error]

ERROR in ./src/browser.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/find-up/index.js:29
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^
SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/pkg-dir/index.js:3:16)
    at Module._compile (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/find-cache-dir/index.js:5:16)
    at Module._compile (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/babel-loader/lib/cache.js:26:22)
    at Module._compile (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/babel-loader/lib/index.js:29:15)
    at Module._compile (/Users/admin/Documents/GitHub/fluid-player-3.0.4/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

npm ERR! Darwin 19.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fluid-player@3.0.4 build: `webpack --mode=production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fluid-player@3.0.4 build script 'webpack --mode=production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fluid-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --mode=production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fluid-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fluid-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/.npm/_logs/2021-06-18T10_07_28_908Z-debug.log
`
[2021-06-18T10_07_28_908Z-debug.log](https://github.com/fluid-player/fluid-player/files/6676324/2021-06-18T10_07_28_908Z-debug.log)

**Comment by leroybm** [comment]
@gibigate Is this still an issue? The build process changed since 3.0.4.

**Comment by sergiomcsousa** [comment]
@gibigate is this still an issue? Can this be close? Thank you!
